#NoEnv
SendMode Input
SetWorkingDir %A_ScriptDir%

; SEC Search Script - Simple version
; Processes 10 contractors, saves raw results for Python parser

; Contractor list (cleaned names, top 100 by project count)
contractors := ["JB FELIPE CONSTRUCTION", "ST TIMOTHY CONSTRUCTION CORPORATION", "E E MADAYAG CONSTRUCTION", "QM BUILDERS", "ALPHA OMEGA GEN CONTRACTOR DEVELOPMENT CORP", "VILLAR GENERAL CONSTRUCTION SUPPLIES", "JLP CONSTRUCTION SUPPLY", "BJMJB CONSTRUCTION SUPPLY", "LEGACY CONSTRUCTION CORPORATION", "DUMAGUETE ZENITH COMMERCIAL", "ROYAL CROWN MONARCH CONSTRUCTION SUPPLIES CORP", "JA OLIVAR ENGG DESIGN", "KIT UBIADAS CONSTRUCTION CORPORATION", "LR TIQUI BUILDERS", "11-16 CONSTRUCTION", "HI-TONE CONSTRUCTION DEVELOPMENT CORPORATION", "FRAMECON BUILDERS", "TRIPLE 8 CONST SUPPLY INC", "IM CONSTRUCTION CORPORATION", "CENTERWAYS CONSTRUCTION AND DEVELOPMENT INC", "RAMSA CONSTRUCTION AND SUPPLY", "FLORDES CONSTRUCTION AND TRADING CORP", "MEGAPOLITAN BUILDERS AND CONSTRUCTION SUPPLY", "MG SAMIDAN CONSTRUCTION", "GOLDEN VISION CONSTRUCTION AND SUPPLY", "FIRST NORTHWAY DEVELOPMENT AND CONSTRUCTION CORPORATION", "CAMCU CONSTRUCTION AND SUPPLIES", "CZMAC CONSTRUCTION SERVICES", "VCD CONSTRUCTION", "ST GERRARD CONSTRUCTION", "ER VENZON CONSTRUCTION", "AC RIVERO DEVELOPMENT CORPORATION", "AC SOLIVEN CONSTRUCTION AND GENERAL MERCHANDISE", "NORTHERN BUILDERS", "FFJJ CONSTRUCTION", "JAGONBUILD CONSTRUCTION CORP", "LARD BUILDERS", "ARM ASIA CONSTRUCTION ENGINEERING", "JWU CONSTRUCTION AND SUPPLY", "DALCON CONSTRUCTION", "IBC INTERNATIONAL BUILDERS CORPORATION", "EQUI-PARCO CONSTRUCTION COMPANY", "739 BUILDERS", "WAWAO BUILDERS", "ROAD EDGE TRADING AND DEVELOPMENT SERVICES", "STO CRISTO CONSTRUCTION AND TRADING", "VERLYNS ENTERPRISES", "SUNWEST", "SUPREME ABF CONSTRUCTION AND CONSTRUCTION SUPPLY COMPANY", "RUDHIL CONSTRUCTION AMP; ENTERPRISES", "REMAR CONSTRUCTION", "NEWBIG FOUR J CONSTRUCTION INC", "FIT CONSTRUCTION", "ROSBILL CONSTRUCTION AND SUPPLY", "GMR CONSTRUCTION AND SUPPLY", "EF CHUA CONSTRUCTION", "BICOL GOLDROCK CONSTRUCTION CORPORATION", "THREE CM BUILDERS", "ORANI BUILDERS SUPPLY", "UYMATIAO TRADING CORPORATION", "EGB CONSTRUCTION", "CT LEONCIO CONSTRUCTION AND TRADING", "ST MATTHEW GEN CONTRACTOR DEVELOPMENT CORP", "BET CONSTRUCTION SUPPLY", "MIGHTYWAY CONSTRUCTION AND SUPPLY", "THREE W BUILDERS", "DRAGON TWELVE BUILDERS AND CONSTRUCTION SUPPLY", "RA PAHATI CONST SUPPLY", "JAIME B CHING ENTERPRISES", "PRECIOUS CONSTRUCTION", "RF FLORES CONSTRUCTION", "RD TALENS CONSTRUCTION AND TRADING", "JEJORS CONSTRUCTION CORPORATION", "AMP CONSTRUCTION", "HEXAMINDZ CORPORATION", "GREAT PACIFIC BUILDERS AND GEN CONTRACTOR INC", "RJIR ENTERPRISES", "ALCEL CONSTRUCTION", "VENRAY CONSTRUCTION CORPORATION", "DAVAO TCM HARDWARE - BRANCH", "SONBLESSED CONSTRUCTION AND SUPPLY", "MV SABALBURO CONSTRUCTION AND SUPPLY", "HGG BUILDERS AND SUPPLY", "LLABAN CONSTRUCTION AND SUPPLY", "LEGACY CONSTRUCTION CORPORATION FORMERLY: LEGACY CONSTRUCTION", "MONOLITHIC CONSTRUCTION AND CONCRETE PRODUCTS", "TOPNOTCH CATALYST BUILDERS INC", "GF ROVERO MERCHANDISING", "EASTERN LINE DEVELOPMENT AND CONSTRUCTION", "RR RICAFORT CONSTRUCTION AND SUPPLIES", "PERSAN CONSTRUCTION", "ASIAN PEARL CONSTRUCTION DEVELOPMENT CORP", "SILVERWOLVES CONSTRUCTION CORPORATION", "STEVEN CONSTRUCTION AND SUPPLY", "5S CONSTRUCTION SUPPLY", "PASCAL CONSTRUCTION", "ANORE CONSTRUCTION", "ACDC ENTERPRISES", "M MONTESCLAROS ENT", "CDU CONSTRUCTION"]

; Open browser
Run msedge.exe --new-window https://checkwithsec.sec.gov.ph/check-with-sec/index
WinWaitActive, ahk_class Chrome_WidgetWin_1, , 10
if ErrorLevel
    ExitApp

WinMaximize
Sleep, 5000

; Navigate to search field once at start
Click, 1, 1
Sleep, 1000
Loop, 9 {
    Send, {Tab}
    Sleep, 300
}

; Process each contractor
Loop, % contractors.MaxIndex() {
    contractorName := contractors[A_Index]
    resultFile := "sec_results\" . StrReplace(contractorName, " ", "_") . ".txt"

    if FileExist(resultFile)
        continue

    Send, ^a
    Sleep, 200
    Send, %contractorName%
    Sleep, 1000
    Send, {Tab}
    Sleep, 300
    Send, {Space}
    Sleep, 8000

    Send, ^a
    Sleep, 500
    Send, ^c
    Sleep, 500

    FileCreateDir, sec_results
    FileAppend, %Clipboard%, %resultFile%

    Send, {Escape}
    Sleep, 200
    Send, {Shift Down}{Tab}{Shift Up}
    Sleep, 300

    TrayTip, Done, %contractorName%, 2
}

WinClose, ahk_class Chrome_WidgetWin_1
ExitApp