#!/usr/bin/env python3
"""
Master script to generate all JSON files in static/data/ directory.
This is the single entry point for updating all cached JSON data.
"""

import os
import sys
import asyncio
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Tuple

class JSONGenerator:
    """Master class to coordinate all JSON file generation."""
    
    def __init__(self):
        self.project_root = Path(__file__).parent.parent.parent
        self.static_data_dir = self.project_root / "static" / "data"
        self.scripts_dir = self.project_root / "sec_scraper"
        self.utils_dir = self.project_root / "utils"
        self.analysis_dir = self.project_root / "analysis"
        
        # Ensure static/data directory exists
        self.static_data_dir.mkdir(parents=True, exist_ok=True)
        
        # JSON file inventory with their generators
        self.json_generators = {
            # SEC and Contractor Data
            'sec_contractors_database.json': {
                'script': 'sec_scraper/generate_sec_json.py',
                'description': 'SEC contractors database from PostgreSQL',
                'category': 'sec_data',
                'dependencies': ['PostgreSQL SEC database']
            },
            'contractor_sec_mapping.json': {
                'script': 'sec_scraper/sec_complete_automation.py',
                'description': 'Contractor SEC mapping data',
                'category': 'sec_data',
                'dependencies': ['SEC database', 'Flood data']
            },
            'excluded_flood_contractors_cache.json': {
                'script': 'sec_scraper/generate_contractors_cache.py',
                'description': 'Cached excluded flood contractors for performance',
                'category': 'cache_data',
                'dependencies': ['PhilGEPS database']
            },
            'contractors_dashboard_cache.json': {
                'script': 'sec_scraper/generate_contractors_dashboard_cache.py',
                'description': 'Complete contractors dashboard cache (SEC, top contractors, Venn, excluded flood)',
                'category': 'cache_data',
                'dependencies': ['SEC database', 'PhilGEPS database']
            },
            
            # Summary Statistics
            'flood_summary.json': {
                'script': 'utils/generate_summary_stats.py',
                'description': 'Flood control projects summary statistics',
                'category': 'summary_data',
                'dependencies': ['Flood API endpoint']
            },
            'dime_summary.json': {
                'script': 'utils/generate_summary_stats.py',
                'description': 'DIME projects summary statistics',
                'category': 'summary_data',
                'dependencies': ['DIME API endpoint']
            },
            'budget_summary.json': {
                'script': 'utils/generate_summary_stats.py',
                'description': 'Budget analysis summary statistics',
                'category': 'summary_data',
                'dependencies': ['Budget API endpoint']
            },
            'nep_summary.json': {
                'script': 'utils/generate_summary_stats.py',
                'description': 'NEP summary statistics',
                'category': 'summary_data',
                'dependencies': ['NEP API endpoint']
            },
            
            # Analysis Results
            'flood_same_amount_proximity_results.json': {
                'script': 'analysis/flood_same_amount_proximity_analysis.py',
                'description': 'Flood projects proximity analysis results',
                'category': 'analysis_data',
                'dependencies': ['Flood control data']
            },
            'contractor_stats_cache.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': 'Contractor statistics cache',
                'category': 'cache_data',
                'dependencies': ['Database queries']
            },
            
            # Geographic Data (usually static, but may need updates)
            'philippines-regions.json': {
                'script': 'Static file (GeoJSON)',
                'description': 'Philippines regions GeoJSON data',
                'category': 'geographic_data',
                'dependencies': ['External GeoJSON source']
            },
            'region-mapping.json': {
                'script': 'Static file (manual update)',
                'description': 'Region mapping data',
                'category': 'geographic_data',
                'dependencies': ['Manual updates']
            },
            
            # Main Data Files (generated by API endpoints)
            'flood_control_data.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': 'Main flood control projects data',
                'category': 'flood_data',
                'dependencies': ['Database queries']
            },
            'flood_baseline_pattern.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': 'Flood baseline patterns',
                'category': 'flood_data',
                'dependencies': ['Database queries']
            },
            
            # Correlation Data
            'flood_dime_contractor_correlation.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': 'Flood-DIME contractor correlation',
                'category': 'correlation_data',
                'dependencies': ['Flood data', 'DIME data']
            },
            'flood_dime_contractor_correlation_2020.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': '2020 Flood-DIME correlation',
                'category': 'correlation_data',
                'dependencies': ['Flood data', 'DIME data']
            },
            'flood_dime_contractor_correlation_2021.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': '2021 Flood-DIME correlation',
                'category': 'correlation_data',
                'dependencies': ['Flood data', 'DIME data']
            },
            'flood_dime_contractor_correlation_2022.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': '2022 Flood-DIME correlation',
                'category': 'correlation_data',
                'dependencies': ['Flood data', 'DIME data']
            },
            'flood_dime_contractor_correlation_2023.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': '2023 Flood-DIME correlation',
                'category': 'correlation_data',
                'dependencies': ['Flood data', 'DIME data']
            },
            'flood_dime_contractor_correlation_2024.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': '2024 Flood-DIME correlation',
                'category': 'correlation_data',
                'dependencies': ['Flood data', 'DIME data']
            },
            'flood_dime_contractor_correlation_2025.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': '2025 Flood-DIME correlation',
                'category': 'correlation_data',
                'dependencies': ['Flood data', 'DIME data']
            },
            'flood_dime_contractor_correlation_all_years.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': 'All years Flood-DIME correlation',
                'category': 'correlation_data',
                'dependencies': ['Flood data', 'DIME data']
            },
            
            # NEP Data
            'nep_2026_infrastructure_categories.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': 'NEP 2026 infrastructure categories',
                'category': 'nep_data',
                'dependencies': ['NEP database']
            },
            'nep_2026_overall_analysis.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': 'NEP 2026 overall analysis',
                'category': 'nep_data',
                'dependencies': ['NEP database']
            },
            'nep_2026_red_flag.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': 'NEP 2026 red flag analysis',
                'category': 'nep_data',
                'dependencies': ['NEP database']
            },
            
            # DIME Data
            'dime_stats.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': 'DIME database statistics',
                'category': 'dime_data',
                'dependencies': ['DIME database']
            },
            'fastest_dime_projects.json': {
                'script': 'API endpoint (generated on-demand)',
                'description': 'Fastest DIME projects analysis',
                'category': 'dime_data',
                'dependencies': ['DIME database']
            }
        }
    
    def print_inventory(self):
        """Print comprehensive inventory of all JSON files and their generators."""
        print("📊 JSON Files Inventory for static/data/")
        print("=" * 60)
        
        categories = {}
        for filename, info in self.json_generators.items():
            category = info['category']
            if category not in categories:
                categories[category] = []
            categories[category].append((filename, info))
        
        for category, files in categories.items():
            print(f"\n📁 {category.replace('_', ' ').title()}")
            print("-" * 40)
            for filename, info in files:
                print(f"  📄 {filename}")
                print(f"     Script: {info['script']}")
                print(f"     Description: {info['description']}")
                print(f"     Dependencies: {', '.join(info['dependencies'])}")
                print()
    
    async def run_script(self, script_path: str, description: str) -> Tuple[bool, str]:
        """Run a Python script and return success status and output."""
        try:
            print(f"🔄 Running {description}...")
            print(f"   Script: {script_path}")
            
            # Change to project root directory
            original_cwd = os.getcwd()
            os.chdir(self.project_root)
            
            try:
                # Run the script
                result = subprocess.run(
                    [sys.executable, script_path],
                    capture_output=True,
                    text=True,
                    timeout=300  # 5 minute timeout
                )
                
                if result.returncode == 0:
                    print(f"✅ {description} completed successfully")
                    return True, result.stdout
                else:
                    print(f"❌ {description} failed with return code {result.returncode}")
                    print(f"   Error: {result.stderr}")
                    return False, result.stderr
                    
            finally:
                os.chdir(original_cwd)
                
        except subprocess.TimeoutExpired:
            print(f"⏰ {description} timed out after 5 minutes")
            return False, "Timeout"
        except Exception as e:
            print(f"❌ Error running {description}: {e}")
            return False, str(e)
    
    async def generate_sec_data(self):
        """Generate SEC-related JSON files."""
        print("\n🏛️ Generating SEC Data...")
        print("=" * 40)
        
        # Generate SEC contractors database
        success, output = await self.run_script(
            'sec_scraper/generate_sec_json.py',
            'SEC Contractors Database'
        )
        
        # Generate excluded flood contractors cache
        success2, output2 = await self.run_script(
            'sec_scraper/generate_contractors_cache.py',
            'Excluded Flood Contractors Cache'
        )
        
        # Generate contractors dashboard cache
        success3, output3 = await self.run_script(
            'sec_scraper/generate_contractors_dashboard_cache.py',
            'Contractors Dashboard Cache'
        )
        
        return success and success2 and success3
    
    async def generate_summary_stats(self):
        """Generate summary statistics JSON files."""
        print("\n📊 Generating Summary Statistics...")
        print("=" * 40)
        
        success, output = await self.run_script(
            'utils/generate_summary_stats.py',
            'Summary Statistics (Flood, DIME, Budget, NEP)'
        )
        
        return success
    
    async def generate_analysis_data(self):
        """Generate analysis results JSON files."""
        print("\n🔍 Generating Analysis Data...")
        print("=" * 40)
        
        # Generate proximity analysis
        success, output = await self.run_script(
            'analysis/flood_same_amount_proximity_analysis.py',
            'Flood Proximity Analysis'
        )
        
        return success
    
    async def generate_all(self, categories: List[str] = None):
        """Generate all JSON files or specific categories."""
        print("🚀 Starting JSON Generation Process")
        print("=" * 50)
        print(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"Target directory: {self.static_data_dir}")
        
        if categories is None:
            categories = ['sec_data', 'summary_data', 'analysis_data']
        
        results = {}
        
        # Generate SEC data
        if 'sec_data' in categories:
            results['sec_data'] = await self.generate_sec_data()
        
        # Generate summary statistics
        if 'summary_data' in categories:
            results['summary_data'] = await self.generate_summary_stats()
        
        # Generate analysis data
        if 'analysis_data' in categories:
            results['analysis_data'] = await self.generate_analysis_data()
        
        # Print results summary
        print("\n📋 Generation Results Summary")
        print("=" * 40)
        for category, success in results.items():
            status = "✅ Success" if success else "❌ Failed"
            print(f"{category.replace('_', ' ').title()}: {status}")
        
        total_success = sum(results.values())
        total_categories = len(results)
        print(f"\nOverall: {total_success}/{total_categories} categories successful")
        
        return results

async def main():
    """Main function to run JSON generation."""
    generator = JSONGenerator()
    
    # Print inventory
    generator.print_inventory()
    
    # Generate all JSON files
    results = await generator.generate_all()
    
    # Check if any failed
    failed_categories = [cat for cat, success in results.items() if not success]
    if failed_categories:
        print(f"\n⚠️  Failed categories: {', '.join(failed_categories)}")
        print("Please check the error messages above and fix any issues.")
        return 1
    else:
        print("\n🎉 All JSON files generated successfully!")
        return 0

if __name__ == "__main__":
    exit_code = asyncio.run(main())
    sys.exit(exit_code)
