#!/usr/bin/env python3
"""
Import incorporator and officer names from parsed PCIJ contractor documents into political_dynasties.

This script reads the JSON files generated by parse_pcij_contractor_documents.py and inserts
all unique names (incorporators and officers) into the political_dynasties table. It also
creates links between politicians and contractors in the politician_contractors table.

Usage:
    $ source .env
    $ python scripts/database/import_pcij_contractor_names.py
"""

from __future__ import annotations

import asyncio
import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

import asyncpg
from dotenv import load_dotenv

load_dotenv()

SOURCE_LABEL = "PCIJ Flood-Control Records (2025-08-30)"
PARSED_DIR = Path(__file__).resolve().parent.parent.parent / "database" / "pcij_parsed"


def split_name(full_name: str) -> Tuple[str, str, Optional[str]]:
    """
    Split a full name into (first_name, last_name, middle_name/suffix).
    
    Handles common patterns:
    - "John Doe" -> ("John", "Doe", None)
    - "John M. Doe" -> ("John", "Doe", "M.")
    - "John Doe Jr." -> ("John", "Doe", "Jr.")
    - "Cezarah Rowena C" -> ("Cezarah Rowena", "C", None)  # Last token might be initial
    """
    full_name = full_name.strip()
    if not full_name:
        return "", "", None
    
    # Remove common prefixes/suffixes that aren't part of the name
    full_name = re.sub(r'^(That|The|A|An)\s+', '', full_name, flags=re.IGNORECASE)
    full_name = full_name.strip()
    
    parts = full_name.split()
    if not parts:
        return "", "", None
    
    if len(parts) == 1:
        # Single token - assume it's a last name
        return "", parts[0], None
    
    # Check if last part is a suffix (Jr., Sr., II, III, etc.)
    last_part = parts[-1].upper()
    suffix_pattern = re.compile(r'^(JR\.?|SR\.?|II|III|IV|V|VI|VII|VIII|IX|X)$')
    if suffix_pattern.match(last_part):
        if len(parts) >= 3:
            return " ".join(parts[:-2]), parts[-2], parts[-1]
        else:
            return parts[0], parts[-2] if len(parts) > 1 else "", parts[-1]
    
    # Check if last part is a single letter (likely an initial)
    if len(parts[-1]) == 1 and parts[-1].isalpha():
        if len(parts) >= 3:
            # "Cezarah Rowena C" -> first="Cezarah Rowena", last="C"
            return " ".join(parts[:-1]), parts[-1], None
        else:
            # "John C" -> first="John", last="C"
            return parts[0], parts[-1], None
    
    # Standard case: last token is last name, everything before is first/middle
    if len(parts) == 2:
        return parts[0], parts[1], None
    else:
        # Multiple parts: first name is first part, last name is last part, middle is everything in between
        return parts[0], parts[-1], " ".join(parts[1:-1]) if len(parts) > 2 else None


def normalize_name(name: str) -> str:
    """Normalize a name for comparison."""
    return " ".join(name.upper().split())


async def ensure_person(
    conn: asyncpg.Connection,
    full_name: str,
    contractor_name: str,
    role: Optional[str] = None,
) -> Optional[int]:
    """
    Ensure a person exists in political_dynasties, creating if necessary.
    
    Returns the person_id if successful, None if name couldn't be parsed.
    """
    first_name, last_name, middle_name = split_name(full_name)
    
    if not first_name or not last_name:
        print(f"⚠️  Skipping unparseable name: {full_name}")
        return None
    
    # Try to find existing person
    existing = await conn.fetchrow(
        """
        SELECT id, first_name, last_name
        FROM political_dynasties
        WHERE UPPER(TRIM(first_name)) = UPPER(TRIM($1))
          AND UPPER(TRIM(last_name)) = UPPER(TRIM($2))
        ORDER BY year DESC NULLS LAST, id DESC
        LIMIT 1
        """,
        first_name,
        last_name,
    )
    
    if existing:
        person_id = existing["id"]
        # Update middle_name if we have new info and existing is empty
        if middle_name and not existing.get("middle_name"):
            await conn.execute(
                """
                UPDATE political_dynasties
                SET middle_name = $1,
                    last_updated = $2
                WHERE id = $3
                """,
                middle_name,
                datetime.utcnow(),
                person_id,
            )
        return person_id
    
    # Create new person
    canonical_first = first_name.upper().strip()
    canonical_full = f"{first_name} {last_name}".upper().strip()
    
    person_id = await conn.fetchval(
        """
        INSERT INTO political_dynasties (
            first_name,
            last_name,
            middle_name,
            canonical_first_name,
            canonical_name,
            last_updated,
            government_branch,
            government_level,
            position_category
        ) VALUES (
            $1, $2, $3, $4, $5, $6, $7, $8, $9
        )
        RETURNING id
        """,
        first_name,
        last_name,
        middle_name,
        canonical_first,
        canonical_full,
        datetime.utcnow(),
        'Private Sector',
        'national',
        'Contractor/Corporate Officer',
    )
    
    print(f"➕ Created: {full_name} (ID: {person_id})")
    return person_id


async def link_person_to_contractor(
    conn: asyncpg.Connection,
    person_id: int,
    contractor_name: str,
    role: Optional[str] = None,
) -> None:
    """Link a person to a contractor in the politician_contractors table."""
    notes = f"From PCIJ flood-control records"
    if role:
        notes += f" - {role}"
    
    await conn.execute(
        """
        INSERT INTO politician_contractors (
            politician_id,
            contractor_name,
            match_confidence,
            notes,
            source,
            created_at,
            updated_at
        ) VALUES ($1, $2, $3, $4, $5, $6, $7)
        ON CONFLICT (politician_id, contractor_name)
        DO UPDATE SET
            notes = EXCLUDED.notes,
            source = EXCLUDED.source,
            updated_at = EXCLUDED.updated_at
        """,
        person_id,
        contractor_name,
        1.0,  # High confidence - from official documents
        notes,
        SOURCE_LABEL,
        datetime.utcnow(),
        datetime.utcnow(),
    )


async def process_contractor_file(conn: asyncpg.Connection, json_path: Path) -> Tuple[int, int]:
    """Process a single contractor JSON file and return (persons_created, persons_linked)."""
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    contractor_name = data.get("contractor_name_guess") or data.get("contractor_slug", "Unknown")
    incorporators = data.get("incorporators", [])
    officers = data.get("officers", [])
    
    persons_created = 0
    persons_linked = 0
    
    # Process incorporators
    for name in incorporators:
        person_id = await ensure_person(conn, name, contractor_name, "Incorporator")
        if person_id:
            persons_created += 1
            await link_person_to_contractor(conn, person_id, contractor_name, "Incorporator")
            persons_linked += 1
    
    # Process officers
    for officer in officers:
        if isinstance(officer, dict):
            name = officer.get("name", "")
            roles = officer.get("roles", [])
            role_label = ", ".join(roles) if roles else "Officer"
        else:
            name = str(officer)
            role_label = "Officer"
        
        if not name:
            continue
        
        person_id = await ensure_person(conn, name, contractor_name, role_label)
        if person_id:
            persons_created += 1
            await link_person_to_contractor(conn, person_id, contractor_name, role_label)
            persons_linked += 1
    
    return persons_created, persons_linked


async def main() -> None:
    """Main entry point."""
    if not PARSED_DIR.exists():
        print(f"❌ Parsed directory not found: {PARSED_DIR}")
        return
    
    json_files = list(PARSED_DIR.glob("*.json"))
    if not json_files:
        print(f"❌ No JSON files found in {PARSED_DIR}")
        return
    
    db_kwargs = {
        "host": os.getenv("POSTGRES_HOST", "localhost"),
        "port": int(os.getenv("POSTGRES_PORT", "5432")),
        "user": os.getenv("POSTGRES_USER", "budget_admin"),
        "password": os.getenv("POSTGRES_PASSWORD", ""),
        "database": os.getenv("POSTGRES_DB_DYNASTY", "dynasty"),
    }
    
    print(f"📥 Processing {len(json_files)} contractor files...")
    
    conn = await asyncpg.connect(**db_kwargs)
    try:
        total_created = 0
        total_linked = 0
        
        for json_path in sorted(json_files):
            print(f"\n📄 Processing {json_path.name}...")
            created, linked = await process_contractor_file(conn, json_path)
            total_created += created
            total_linked += linked
        
        print(f"\n✅ Complete!")
        print(f"   Persons created/updated: {total_created}")
        print(f"   Contractor links created: {total_linked}")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())

