#!/usr/bin/env python3
"""
Import DPWH infrastructure contract data into the philgeps.dpwh_procurement table.

Reads the CSV output generated by the dpwh-infra-data-scraper project and upserts
each contract into the philgeps database, handling duplicates by contract_id
and checkpointed CSV runs.
"""

from __future__ import annotations

import argparse
import asyncio
import csv
import os
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, date
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import asyncpg


@dataclass
class ContractRecord:
    contract_id: str
    project_name: str
    description: str
    region: Optional[str]
    implementing_office: Optional[str]
    source_of_funds: Optional[str]
    project_cost: Optional[Decimal]
    effectivity_date: Optional[date]
    expiry_date: Optional[date]
    status: Optional[str]
    contractor_names: List[str]
    bidders: List[str]
    file_source: Optional[str]
    year: Optional[int]


def parse_decimal(value: str) -> Optional[Decimal]:
    if not value:
        return None
    try:
        return Decimal(value)
    except (InvalidOperation, ValueError):
        return None


def parse_date(value: str) -> Optional[date]:
    if not value:
        return None
    try:
        return datetime.strptime(value, "%Y-%m-%d").date()
    except ValueError:
        return None


def normalise_contractors(row: Dict[str, str]) -> Tuple[List[str], List[str]]:
    names: List[str] = []
    ids: List[str] = []
    for idx in range(1, 5):
        name_key = f"contractor_name_{idx}"
        id_key = f"contractor_id_{idx}"
        raw_name = (row.get(name_key) or "").strip()
        raw_id = (row.get(id_key) or "").strip()
        if not raw_name:
            continue
        if idx == 4:
            split_names = [part.strip() for part in raw_name.split(";") if part.strip()]
            split_ids = [part.strip() for part in raw_id.split(";") if part.strip()]
            names.extend(split_names)
            ids.extend(split_ids)
        else:
            names.append(raw_name)
            if raw_id:
                ids.append(raw_id)
    return names, ids


def choose_latest(existing: ContractRecord, candidate: ContractRecord) -> ContractRecord:
    if not existing.file_source:
        return candidate
    if not candidate.file_source:
        return existing
    return candidate if candidate.file_source > existing.file_source else existing


def load_contracts(csv_path: Path) -> Dict[str, ContractRecord]:
    records: Dict[str, ContractRecord] = {}
    with csv_path.open("r", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            contract_id = (row.get("contract_id") or "").strip()
            if not contract_id:
                continue

            project_name = (row.get("description") or "").strip()
            region = (row.get("region") or "").strip() or None
            implementing_office = (row.get("implementing_office") or "").strip() or None
            source_of_funds = (row.get("source_of_funds") or "").strip() or None
            project_cost = parse_decimal((row.get("cost_php") or "").strip())
            effectivity = parse_date((row.get("effectivity_date") or "").strip())
            expiry = parse_date((row.get("expiry_date") or "").strip())
            status = (row.get("status") or "").strip() or None
            file_source = (row.get("file_source") or "").strip() or None
            year_value = row.get("year")
            year = None
            if year_value:
                try:
                    year = int(year_value)
                except ValueError:
                    year = None

            contractor_names, contractor_ids = normalise_contractors(row)
            bidders: List[str] = contractor_names.copy()
            if contractor_ids:
                bidders.extend(contractor_ids)

            candidate = ContractRecord(
                contract_id=contract_id,
                project_name=project_name,
                description=project_name,
                region=region,
                implementing_office=implementing_office,
                source_of_funds=source_of_funds,
                project_cost=project_cost,
                effectivity_date=effectivity,
                expiry_date=expiry,
                status=status,
                contractor_names=contractor_names,
                bidders=bidders,
                file_source=file_source,
                year=year,
            )

            if contract_id in records:
                records[contract_id] = choose_latest(records[contract_id], candidate)
            else:
                records[contract_id] = candidate

    return records


async def ensure_indexes(conn: asyncpg.Connection) -> None:
    await conn.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_indexes
                WHERE schemaname = 'public'
                  AND indexname = 'idx_dpwh_procurement_contract_unique'
            ) THEN
                CREATE UNIQUE INDEX idx_dpwh_procurement_contract_unique
                    ON dpwh_procurement (contract_id);
            END IF;
        END$$;
        """
    )


def build_upsert_payload(record: ContractRecord) -> Tuple:
    contractor_primary = "; ".join(record.contractor_names) if record.contractor_names else None
    bidders_array = record.bidders if record.bidders else None
    if record.source_of_funds:
        if record.description:
            project_description = f"{record.description} | Source of Funds: {record.source_of_funds}"
        else:
            project_description = f"Source of Funds: {record.source_of_funds}"
    else:
        project_description = record.description or None
    return (
        record.contract_id,
        None,  # procurement_id not provided by dataset
        record.project_name or None,
        record.region or None,
        record.implementing_office or None,
        record.project_cost,
        contractor_primary,
        bidders_array,
        project_description,
        record.effectivity_date,
        record.effectivity_date,
        record.expiry_date,
        record.file_source or None,
        record.file_source or None,
    )


UPSERT_SQL = """
INSERT INTO dpwh_procurement (
    contract_id,
    procurement_id,
    project_name,
    location,
    procuring_entity,
    project_cost,
    contractor_name,
    bidders,
    project_description,
    bid_opening_date,
    issuance_start_date,
    issuance_end_date,
    zip_filename,
    pdf_filename,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, CURRENT_TIMESTAMP
)
ON CONFLICT (contract_id) DO UPDATE SET
    procurement_id = EXCLUDED.procurement_id,
    project_name = EXCLUDED.project_name,
    location = EXCLUDED.location,
    procuring_entity = EXCLUDED.procuring_entity,
    project_cost = EXCLUDED.project_cost,
    contractor_name = EXCLUDED.contractor_name,
    bidders = EXCLUDED.bidders,
    project_description = EXCLUDED.project_description,
    bid_opening_date = EXCLUDED.bid_opening_date,
    issuance_start_date = EXCLUDED.issuance_start_date,
    issuance_end_date = EXCLUDED.issuance_end_date,
    zip_filename = EXCLUDED.zip_filename,
    pdf_filename = EXCLUDED.pdf_filename,
    updated_at = CURRENT_TIMESTAMP;
"""


async def upsert_records(
    conn: asyncpg.Connection,
    records: Iterable[ContractRecord],
    batch_size: int = 500,
) -> int:
    total = 0
    batch: List[Tuple] = []
    for record in records:
        batch.append(build_upsert_payload(record))
        if len(batch) >= batch_size:
            await conn.executemany(UPSERT_SQL, batch)
            total += len(batch)
            batch.clear()
    if batch:
        await conn.executemany(UPSERT_SQL, batch)
        total += len(batch)
    return total


async def run_import(args: argparse.Namespace) -> None:
    csv_path = Path(args.csv_path)
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_path}")

    print(f"Loading contracts from {csv_path} ...")
    records = load_contracts(csv_path)
    print(f"Prepared {len(records)} unique contracts.")

    if args.dry_run:
        sample = next(iter(records.values()))
        print("Dry-run mode. Sample payload:")
        print(build_upsert_payload(sample))
        return

    db_config = {
        "host": os.getenv("POSTGRES_HOST", "localhost"),
        "port": int(os.getenv("POSTGRES_PORT", 5432)),
        "user": os.getenv("POSTGRES_USER", "budget_admin"),
        "password": os.getenv("POSTGRES_PASSWORD", ""),
        "database": os.getenv("POSTGRES_DB_PHILGEPS", "philgeps"),
    }

    conn = await asyncpg.connect(**db_config)
    try:
        await ensure_indexes(conn)
        processed = await upsert_records(conn, records.values())
        print(f"Upserted {processed} contracts into dpwh_procurement.")
    finally:
        await conn.close()


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Import DPWH contracts into philgeps.dpwh_procurement")
    parser.add_argument(
        "--csv-path",
        type=Path,
        default=Path.home() / "dpwh-infra-data-scraper" / "csv" / "contracts_all_years_all_offices.csv",
        help="Path to the contracts CSV file (default: dpwh-infra-data-scraper/csv/contracts_all_years_all_offices.csv)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Load and parse CSV but do not write to the database.",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    try:
        asyncio.run(run_import(args))
    except Exception as exc:
        print(f"Import failed: {exc}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

